from torchimize.functions.single.gna_fun_single import lsq_gna
from torchimize.functions.single.lma_fun_single import lsq_lma
from torchimize.functions.parallel.gna_fun_parallel import lsq_gna_parallel, lsq_gna_parallel_plain
from torchimize.functions.parallel.lma_fun_parallel import lsq_lma_parallel
from torchimize.functions.parallel.newton_parallel import newton_step_parallel
from torchimize.functions.fun_dims import test_fun_dims_parallel